spring:
  profiles:
    active:
      - local

---

spring:
  config:
    activate:
      on-profile:
        - local
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/product-service?authSource=admin

