spring:
  profiles:
    active:
      - local

---

spring:
  config:
    activate:
      on-profile:
        - local
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/product-service?authSource=admin

springdoc:
  swagger-ui:
    path: /swagger-ui.html

  api-docs:
    path: /api-docs